---
- name: Install Mysql
  apt:
    name: mysql-server
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present   

- name: Create a new database with name {app_name}
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: chiio
    state: present

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: ''
    host_all: yes
    state: absent

- name: Create database user with name {app_name} and password {password} with all database privileges on {app_name}
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: chiio
    password: secret
    priv: "chiio.*:ALL"
    state: present