---
- hosts: all
  name: Ravel Ops Setup
  become: yes

  tasks:
  - name: Add repository for PHP versions (Ubuntu).
    apt_repository: repo='ppa:ondrej/php'

  - name: Install PHP
    apt:
      name:
        - php8.2
        - php8.2-fpm
        - php8.2-common
        - php8.2-zip
        - php8.2-curl
        - php8.2-xml
        - php8.2-ldap
        - php8.2-imap
        - php8.2-mbstring
        - php8.2-mysql
        - php8.2-pdo
        - php8.2-intl
        - php8.2-cli
        - php8.2-bcmath
        - php8.2-opcache
        - php8.2-pgsql
        - php8.2-pdo
        - php8.2-redis
        - php-xdebug
      state: present

  - name: Install composer
    include_role:
      name: composer

  - name: Install node
    include_role:
      name: node

  - name: Install Redis
    apt:
      name: redis
      state: present

  - name: Install Supervisor
    apt:
      name: supervisor
      state: present    

  - name: Install Mysql
    include_role:
      name: mysql

  - name: Install nginx
    include_role:
      name: nginx